
CREATE TABLE `ecs_instance` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ecs_type` varchar(50) NOT NULL DEFAULT '' COMMENT 'ecs实例类型',
  `instance_id` varchar(150) NOT NULL DEFAULT '' COMMENT '实例id',
  `region_id` varchar(50) NOT NULL DEFAULT '' COMMENT '地域ID',
  `image_id` varchar(150) NOT NULL DEFAULT '' COMMENT '镜像ID',
  `security_group_ids` varchar(250) NOT NULL DEFAULT '' COMMENT '安全组ID集合',
  `expire_date` date COMMENT '到期日',
  `v_switch_id` varchar(100) NOT NULL DEFAULT '' COMMENT '虚拟交换机ID',
  `instance_type` varchar(150) NOT NULL DEFAULT '' COMMENT '实例的资源规格',
  `internet_max_bandwidth_in` int(4) DEFAULT 0 COMMENT '公网入带宽最大值',
  `internet_max_bandwidth_out` int(4) DEFAULT 0 COMMENT '公网出带宽最大值',
  `instance_name` varchar(150) NOT NULL DEFAULT '' COMMENT '实例名称',
  `host_name` varchar(150) NOT NULL DEFAULT '' COMMENT '云服务器的主机名',
  `inner_ip` varchar(150) NOT NULL DEFAULT '' COMMENT '内网IP',
  `username` varchar(50) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` varchar(50) NOT NULL DEFAULT '' COMMENT '密码',
  `port` int(8) NOT NULL DEFAULT 22 COMMENT 'ssh登陆端口',
  `description` varchar(256)  DEFAULT '' COMMENT '实例的描述',
  `system_disk_size` varchar(50)  DEFAULT '' COMMENT '系统盘大小',
  `system_disk_category` varchar(50)  DEFAULT '' COMMENT '系统盘的磁盘种类',
  `auto_release_time` varchar(50)  DEFAULT '' COMMENT '自动释放时间（按量）',
  `internet_charge_type` varchar(50)  DEFAULT '' COMMENT '网络计费类型，PayByBandwidth：按固定带宽计费，PayByTraffic（默认）：按使用流量计费',
  `period` int(4)  DEFAULT 0 COMMENT '购买资源的时长',
  `auto_renew` int(1)  DEFAULT 0 COMMENT '是否要自动续费，0：不自动续费 1：自动续费',
  `instance_charge_type` varchar(50)  DEFAULT '' COMMENT '实例的付费方式，PrePaid：预付费，包年包月，PostPaid（默认）：按量付费',
  `status` int(1) NOT NULL DEFAULT '0' COMMENT '状态，0什么都没做，1 准备中：Pending，2 启动中：Starting，3 运行中：Running，4 停止中：Stopping，5 已停止：Stopped，6 释放：deleted',
  `period_unit` varchar(50)  DEFAULT '' COMMENT '购买资源的时长，Week Month',
  `create_user` varchar(150) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user` varchar(150) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后一次修改时间',
  PRIMARY KEY (`id`),
  KEY `instance_id_index` (`instance_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ECS实例表';